bump to opencv 3.4.2, add support for different camera sensors, increase USB buffer

diff --git a/jevois-build/jevois-flash-card b/jevois-build/jevois-flash-card
--- a/jevois-build/jevois-flash-card
+++ b/jevois-build/jevois-flash-card
@@ -15,23 +15,24 @@ if [ ! -d /var/lib/jevois-microsd ]; then
     exit 1
 fi
 
-if [ ! -d /var/lib/jevois-microsd/modules ]; then
-    echo "Directory /var/lib/jevois-microsd/modules/ is missing -- run [./rebuild-platform.sh --staging] in jevoisbase -- ABORT"
-    exit 2
-fi
-
 if [ ! -d /var/lib/jevois-build ]; then
     echo "Directory /var/lib/jevois-build/ is missing -- run [./rebuild-platform.sh] in jevois -- ABORT"
     exit 3
 fi
 
-if [ ! -d /var/lib/jevois-build/boot ]; then
-    echo "Directory /var/lib/jevois-build/boot is missing -- run [./jevois-build.sh] in jevois-sdk -- ABORT"
-    exit 4
-fi
 if [ ! -d /var/lib/jevois-build/usr ]; then
     echo "Directory /var/lib/jevois-build/usr is missing -- run [./rebuild-platform.sh] in jevois -- ABORT"
     exit 5
+fi
+
+if [ ! -d /var/lib/jevois-microsd/modules ]; then
+    echo "Directory /var/lib/jevois-microsd/modules/ is missing -- run [./rebuild-platform.sh --staging] in jevoisbase -- ABORT"
+    exit 2
+fi
+
+if [ ! -d /var/lib/jevois-build/boot ]; then
+    echo "Directory /var/lib/jevois-build/boot is missing -- run [./jevois-build.sh] in jevois-sdk -- ABORT"
+    exit 4
 fi
 
 ####################################################################################################
